POST http://localhost:3003/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWM0NDhjYmU3ZmU1OTdkZjk1ZThhNGYiLCJlbWFpbCI6Im5pa2hpbDBAa3VtYXIuY29tIiwiaWF0IjoxNzc0NDcyMTI4LCJleHAiOjE3NzQ1NTg1Mjh9.0YM9_hW9CJZfG3JIxgI18m2o_NhsO1zu0s9UFl1ck6k

{
    "title":"coding python is fun",
    "description":"i dont love python",
    "status":"inProgress",
    "priority":"normal",
    "dueDate":"2025-12-01"
} 